#!/usr/bin/zsh
readonly \
  RED='#[fg=#dc322f]' \
  GREEN='#[fg=#859900]' \
  COLOR_OFF='#[fg=colour7]'

acpi -b \
  | grep -Eoz -e '[0-9][0-9]?[0-9]?\%' -e "Full|Charging|Discharging|Unknown" \
  | read charge_status charge_percentage

case $charge_status in
  Charging)
    print "${GREEN}${charge_percentage}${COLOR_OFF}"
    ;;
  Discharging)
    print "${RED}${charge_percentage}${COLOR_OFF}"
    ;;
  Unknown|Full)
    print "${COLOR_OFF}${charge_percentage}"
    ;;
  *)
  printf "${COLOR_OFF}$(</proc/sys/kernel/random/entropy_avail)"
esac


