#!/usr/bin/zsh
setopt extendedglob

readonly \
  SCRIPT_NAME="${0:t}" \
  SRCDIR="${0:A:h}/src"
  DOTDIR="${0:A:h}/dots"

alias exists="> /dev/null type -p"

. ${SRCDIR}/options
. ${SRCDIR}/dependencies
. ${SRCDIR}/installd

finish () {
  rm -rf /tmp/package-query
  rm -rf /tmp/yaourt
  rm -rf /tmp/dzvol
  rm -f  /tmp/installer.sh
}

usage () {
  cat <<EOF
usage: ${SCRIPT_NAME} [-aztnxi]
       ${SCRIPT_NAME} [-aztnxu]

  -a      Install all dotfiles
  -i      Install package dependencies for chosen dotfiles
  -u      Uninstall chosen dotfiles
  -z      Install Zsh dotfiles
  -t      Install Tmux dotfiles
  -g      Install GHCi dotfiles
  -n      Install Neovim dotfiles
  -x      Install X11 dotfiles
  -h      Print this usage message
EOF
}

main () {
  trap "trap - SIGTERM && finish && kill -- -$$" SIGINT SIGTERM

  local -Ua \
    FLAGS \
    missing_dependencies

  # archlinux dependencies TODO add other distros TODO
  local -Ar YAOURT_DEPENDENCIES=( \
      zsh "antibody lsof trash-cli git" \
      ghci "ghc haskell-stack haskell-hscolour haskell-pretty-show" \
      tmux "tmux bind-tools git powerline-fonts-git" \
      neovim "neovim python-neovim python \
            ghc-mod rust-racer clang shellcheck \
            eslint tidy go git" \
      x11 "xmonad qutebrowser mpv xss-lock-git xautolock \
      xbanish unclutter-xfixes-git slock xorg-xsetroot \
      compton xmonad-contrib scrot xorg-xset git"
  )

  options $@

  dependencies

  installd
}

 main $@
