#!/usr/bin/zsh
terminal="st"

if ! pgrep -x ${terminal}; then
  if ! pgrep -x "tmux: server"; then
    ${terminal} -e tmux new-session -s $(whoami)&!; else
    ${terminal} -e tmux attach-session -t $(whoami)&!
  fi
fi

if ! pgrep -f qutebrowser; then
  qutebrowser --backend webengine&!
fi
